name: newman action run

on: pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: matt-ball/newman-action@master
        with:
          collection: 18507875-41095035-c383-49ab-8553-a353132a1924
