name: scenarigo run

on: pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TARGET_ENV: prod
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16.3

      - uses: actions/checkout@v2

      - name: Get dependencies
        run: ./scripts/bootstrap

      - name: Run scenarigo
        run: ./scripts/scenarigo_run -e ${{ env.TARGET_ENV }}
